###############################################################################
# ENVIRONMENT SPECIFIC CONFIGURATIONS
###############################################################################

# Serverless Framework Configurations
sls:
  deploymentBucketName: my-dummy-s3-bucket
  region: us-west-2
  accountid: 000000000000
  ph_env: local

  # KMS For SSM
  # Managed by terraform
  kms_for_ssm_arn: arn:aws:kms:${self:provider.region}:${self:custom.accountid}:key/dummy

  # VPC Configs
  vpcID: vpc-000000000000
  vpc:
    securityGroupIds:
    - sg-000000000000
    subnetIds:
    - subnet-000000000000

# Application Configurations
app:
  LOG_LEVEL: debug
  PH_TLD: local
  NODE_ENV: local
  EXTERNAL_REQUEST_TIMEOUT: 30000
# Jenkins
jenkins:
  job_iam_role: arn:aws:iam::000000000000:role/dummy

###############################################################################
