###############################################################################
# ENVIRONMENT SPECIFIC CONFIGURATIONS
###############################################################################

# Serverless Framework Configurations
sls:
  deploymentBucketName: ph-devops-serverless-${self:provider.region}
  region: us-west-2
  accountid: 779038906119
  ph_env: prod

  # KMS For SSM
  # Managed by terraform
  kms_for_ssm_arn: arn:aws:kms:${self:provider.region}:${self:custom.accountid}:key/aef7c4e6-718e-4e5a-8627-f9f7a680b84a

  # VPC Configs
  vpcID: vpc-5027ea35
  vpc:
    securityGroupIds:
    - Ref: lambdaSecurityGroup
    subnetIds:
    - subnet-936e70d5
    - subnet-204ee056
    - subnet-ff67f09b

# Application Configurations
app:
  LOG_LEVEL: debug
  PH_TLD: com
  NODE_ENV: production
  EXTERNAL_REQUEST_TIMEOUT: 30000
  
# Jenkins
jenkins:
  job_iam_role: arn:aws:iam::779038906119:role/jenkins-deployer-serverless

###############################################################################
